### ISSUE TITLE
Trying to experiment with this. wasmTextToBinary is not defined

### ISSUE THREAD

**Issue by sabine** [lars-t-hansen/moz-gc-experiments#16]
I downloaded Firefox Developer Edition 76.0b5 (64-bit).
I set `javascript.options.wasm_gc` to `true`.
I call `wasmTextToBinary()`.
I get
```ReferenceError: wasmTextToBinary is not defined```

What do I need to do in order to use `wasmTextToBinary()`?

**Comment by lars-t-hansen** [comment]
wasmTextToBinary is unfortunately only available in the JS shell, it's not in the browser.  If using the JS shell is enough for your experimentation (which seems plausible, at least), then you can just use that.

If you need wasm code to run in the browser then you have various options:
- if wabt (https://github.com/webassembly/wabt) supports the opcodes then you can use wabt to produce binary wasm code from text
- you can write a little script to compile textual wasm to binary wasm using the JS shell + wasmTextToBinary, it's definitely possible but it's less simple than it ought to be
- you can generate binary wasm code directly from your program and run that

There's work underway to make wabt, Firefox/SpiderMonkey, and Chrome/v8 agree on the encodings for the experimental GC features, but that work is not finished yet, and I'm not sure how compatible wabt is with spidermonkey at the moment.  Maybe @eqrion can tell us.

**Comment by sabine** [comment]
Great, thank you! I guessed I was doing something trivial wrong, just not what. The shell is perfectly fine for my purposes.

I'll give the `wasmTextToBinary` approach a go and see how that works out, for now. I'n the `.wat` code, I have all the variable names and type names, which makes it much easier to debug than plain wasm.

I'll be experimenting with memory representations for OCaml in WebAssembly in order to find out how compiling to WASM+GC turns out in comparison to compiling to linear memory and shipping our own GC.

There is indeed so much going on and people are putting in a lot of work. It's great to see that. 👍

**Comment by lars-t-hansen** [comment]
Great to hear, thanks.  Don't forget to look at #15 - documentation in this repo may not be current, depending on what patches have landed lately.
