### ISSUE TITLE
Output from wasmTextToBinary() can not compiled

### ISSUE THREAD

**Issue by Horcrux7** [lars-t-hansen/moz-gc-experiments#3]
I hope this is the right place here for the problem. If not I can post it again on a different place.
I receive the errors:

`CompileError: wasm validation error: at offset 23: Structure types not enabled`

and 

`CompileError: wasm validation error: at offset 29: reference types not enabled`

if I try to compile the output of wasmTextToBinary() with  WebAssembly.compile(). If I try to analyze the output of wasmTextToBinary with some tools I receive:  `error: invalid section code: 42; max is 11`
This means the marker section is written but some is wrong like the position of the section.

The wat is very simple:

```
(module
  (gc_feature_opt_in 2)
  (type $Abc (struct
    (field $a i32)
    (field $b i64)
  ))
)
```

I use the nightly build version `JavaScript-C66.0a1`.

**Comment by lars-t-hansen** [comment]
For the time being, you need to turn on javascript.options.wasm_gc in about:config in order to use reference types and the experimental gc types.  I see the documentation is not at all clear about this; I will update it.  Thanks.
