### ISSUE TITLE
There are no flags in type declaration

### ISSUE THREAD

**Issue by Horcrux7** [lars-t-hansen/moz-gc-experiments#5]
The flags in the type section between `form` and `field_count` seems an error in the documentation.

```
form         varint7        0x50 = SLEB(-0x30), represents "struct constructor"
flags        varint7        no flags at present
field_count  varuint32
```
Should be
```
form         varint7        0x50 = SLEB(-0x30), represents "struct constructor"
field_count  varuint32
```
I can not see this flag in the output of wasmTextToBinary() and it work for me in the binary format without the flag.

**Comment by lars-t-hansen** [comment]
I can confirm that none of text->binary, binary->text, or binary parsing expect a flag here.  Probably old prose, I will update as soon as I have the chance.  Thanks!
