### ISSUE TITLE
What is the syntax for locals with struct type?

### ISSUE THREAD

**Issue by Horcrux7** [lars-t-hansen/moz-gc-experiments#6]
I try to use to declare a local variable with a type of a struct but I am unclear over the syntax. I can not find a syntax that work.
```
(module (gc_feature_opt_in 3)
  (type $Abc (struct
    (field $a (mut i32))
    (field $b (mut i64))
  ))
  (func $simple (result i32) (local $val $Abc)
    i32.const 0
    i64.const 0
    struct.new $Abc
    local.tee $val
    i32.const 63
    struct.set $Abc $a
    local.get $val
    struct.get $Abc $a
    return
  )
)
```

**Comment by lars-t-hansen** [comment]
The syntax is `(local (ref $Abc))`.  Note that there are no locals of struct type; there are only locals of references to struct type.

**Comment by Horcrux7** [comment]
Thank you. This solve the problem. As Java developer I forgot ever the difference between reference and value. In Java all is a reference.
