### ISSUE TITLE
Crash with linked list

### ISSUE THREAD

**Issue by Horcrux7** [lars-t-hansen/moz-gc-experiments#9]
Sorry, but I have the next problem. It look like a crash of SpiderMonkey. I want test the behavior of the GC and have create a large linked list. The follow Java code:

```
@Export
static int simple() {
    Abc2 val = new Abc2();
    for( int i = 0; i < 100_000; i++ ) {
        val.abc = new Abc2();
    }
    val.a = 63;
    return val.a;
}
```
compile to the follow WAT code:
```
(module (gc_feature_opt_in 3)
  (export "simple" (func $simple))
  (type $Abc2 (struct
    (field $Abc2.a (mut i32))
    (field $Abc2.b (mut i64))
    (field $Abc2.abc (mut anyref))
  ))
  (func $simple (result i32) (local $val (ref $Abc2)) (local $i i32) (local (ref $Abc2))
    i32.const 0
    i64.const 0
    ref.null
    struct.new $Abc2
    local.set $val
    i32.const 0
    local.set $i
    block
      loop
        local.get $i
        i32.const 100000
        i32.ge_s
        br_if 1
        local.get $val
        i32.const 0
        i64.const 0
        ref.null
        struct.new $Abc2
        struct.set $Abc2 2 ;; $abc
        local.get $i
        i32.const 1
        i32.add
        local.set $i
        br 0
      end
    end
    local.get $val
    i32.const 63
    struct.set $Abc2 0 ;; $a
    local.get $val
    struct.get $Abc2 0 ;; $a
    return
  )
)
```
If I run this code then SpiderMonkey terminate with the exit code -1073741819 (0x‭C0000005‬). I think this is a Access Violation.
I run https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/jsshell-win64.zip under Windows 10.
The error is reproducible on every run. I have use the command line options `--wasm-gc --wasm-verbose`

**Comment by lars-t-hansen** [comment]
OK.  Will move this to bugzilla.  Please file crash bugs against the Core :: WebAssembly component in Bugzilla, that way we can control visibility if it becomes important.

**Comment by lars-t-hansen** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1546157
